### ISSUE TITLE
blog demo

### ISSUE THREAD

**Issue by rootsmusic** [microsoft/powerbi-desktop-samples#22]
Where can I find these demos?  Thanks.

**Comment by Daandamhuis** [comment]
Look for the update video's: https://www.youtube.com/user/mspowerbi/videos
Look for the blog posts: https://powerbi.microsoft.com/nl-nl/blog/category/announcements/

**Comment by guyinacube** [comment]
The PBIX files, for the monthly Power BI Desktop releases are in the Year folders and are associated with the monthly blog announcements and associated YouTube video as @Daandamhuis mentioned.
