### ISSUE TITLE
Supply Chain Sample.pbix not opening in Power BI Desktop due to sensivitiy labelling

### ISSUE THREAD

**Issue by shouvikbasu** [microsoft/powerbi-desktop-samples#46]
Downloaded the report but not opening in Power BI Desktop due to sensivitiy labelling.

![Capture](https://user-images.githubusercontent.com/50727210/192193629-6b3cd366-4649-4c2d-933b-5b461faa7997.PNG)

**Comment by jeroenterheerdt** [comment]
@emlisa these files came with your PR (#45).. any chance you can help troubleshoot this?

**Comment by jeroenterheerdt** [comment]
thanks for reporting this @shouvikbasu! We have updated the files and you should be able to open them now, can you please check?

**Comment by shouvikbasu** [comment]
Wow.. thank you for the prompt response. The issue is resolved and I can open the file in Power BI Desktop.
Really appreciate this work you are doing.

**Comment by jeroenterheerdt** [comment]
thanks for your kind words @shouvikbasu! glad to hear the issue has been resolved.
