### ISSUE TITLE
Report Theme Json Schema: Applying settings according to State of button.

### ISSUE THREAD

**Issue by gopakumarlimner** [microsoft/powerbi-desktop-samples#50]
@yelper 

Hi, I am using the json schema to create a custom theme in Visual Studio Code. The autocomplete is not showing options when we want to set Text/Fill etc for different states in Page Navigator/ other buttons which have different states. How do we set this per state? 
![image](https://user-images.githubusercontent.com/66367870/220192086-9759c2dd-bf9c-4509-b1c7-1c6edc1e7d3f.png)

**Comment by yelper** [comment]
You can use the `"$id"` property to mark a property bag for a particular state.  For page/bookmark navigator, the valid values for `$id` are `default`, `hover`, `pressed`, and `selected`.  For actionButton, the valid values are `default`, `hover`, `pressed`, and `disabled`.  For filterCard, the valid values are `Available` and `Applied`.  

Here's an example theme to set the hover fill color to #f3f3f3 and the default/resting color to #00ff00.  I made task #1036688 internally to potentially add this info to the schema.

```json
{
    "name": "Custom Theme",
    "$schema": "https://raw.githubusercontent.com/microsoft/powerbi-desktop-samples/main/Report%20Theme%20JSON%20Schema/reportThemeSchema-2.114.json",
    "visualStyles": {
        "pageNavigator": {
            "*": {
                "fill": [
                    {
                        "fillColor": { "solid": { "color": "#00ff00" } }
                    },
                    {
                        "$id": "hover",
                        "fillColor": { "solid": { "color": "#f3f3f3" } }
                    }
                ]
            }
        }
    }
}
```

**Comment by MikeCarlo** [comment]
Is this being added to the Theme Spec? 

I have another person asking about this being included in the theme spec, and ultimately within the theme builder tool. 

cc: @yelper
