### ISSUE TITLE
Vertical Alignement enum refers horizontal alignment

### ISSUE THREAD

**Issue by CharlesSaulnier** [microsoft/powerbi-desktop-samples#52]
the actionButton object does not have the right properties for verticalAlignment. It refers to the same enum as horizontalAlignment

`"alignment": {
            "type": "string",
            "enum": [
                "left",
                "center",
                "right"
            ]`

This breaks our current theme since the value "middle" was accepted before, and IMO does not make sense with the values from any format setting (at least _left_ and _right_ do not make sense for verticalAlignment)

**Comment by yelper** [comment]
Yep, this is a known issue as reported by others.  I apologize for the inconvenience -- we'll be pushing an update with the release of March's Desktop.  (internal ref #1031111)
