### ISSUE TITLE
Report theme JSON schema - Accept comments

### ISSUE THREAD

**Issue by OscarValerock** [microsoft/powerbi-desktop-samples#55]
Hi, would it be possible to add a "comment" field to all the properties?

Before the big release of the new JSON themes, this was possible, unfortunately today, we can't add commments. 

Sometimes naming is not intuitive, and it comes in handy for theme development.  Thanks!

@yelper 

![image](https://user-images.githubusercontent.com/60475729/222905849-3906bbf6-4ec2-4435-9796-53fe6b307dda.png)

**Comment by yelper** [comment]
There's definitely a balance to be struck here! Part of making the set of properties restrictive is to make it obvious when there's a typo, like you specify `"colro": "#001A29"` and it errors.  Right now, I believe only the textClasses, styles-level of visualStyles (second level), fill rules, icon definitions, and data bars definitions are restrictive.  

We believed these to be the places where we should be restrictive to prevent setting properties not known by these types and catch these sort of typos.
