### ISSUE TITLE
Enumeration values are not valid for labelOrientation

### ISSUE THREAD

**Issue by somedaygone** [microsoft/powerbi-desktop-samples#57]
When using the enumeration for labelOrientation, it yields an error.

    "labelOrientation": "horizontal",
    "labelOrientation": "vertical",

<img width="351" alt="image" src="https://user-images.githubusercontent.com/4382563/223806795-4ca84c5a-41bc-46d7-8143-0945df913509.png">

The Schema should have something like:
````
                          "labelOrientation": {
                            "type": "string",
                            "enum": [
                              "horizontal",
                              "vertical"
                            ],
                            "title": "Orientation"
                          },
````
(Not sure if your convention is caps or lower, and not sure which value is 0 and which is 1!)

**Comment by somedaygone** [comment]
FYI, it looks like this similar issue may apply to other properties like `radiusScalingMethod`, `barShape`, `orientation`, `expandCollapseToggleType`, and `position`.

Try doing a find on integer enums:
````
"type": "integer",
                            "enum"
````
My search found 34 occurrences that need to be updated for these properties.

**Comment by yelper** [comment]
The error is correct, 0 and 1 are the only allowed values for `label > labelOrientation`.  A type of "integer" and "enum" means that the values must be integers and also one of the listed values.  0 is vertical, and 1 is horizontal.

If you spot another issue, please let me know.  I'll work on making this a bit more descriptive; the values of 0 and 1 are hard to discern.  I'll probably end up [following the convention described here](https://github.com/json-schema-org/json-schema-spec/issues/57#issuecomment-247861695), but this likely won't make it until the May Desktop release.

**Comment by somedaygone** [comment]
Sorry, just saw the link. Yes, adding a title on each integer would work. I think strings would match what is being used elsewhere, but I'm guessing that requires code changes elsewhere that won't happen for a long time. Thanks for taking this up!

**Comment by yelper** [comment]
I've prototyped something for the May release, it'll look something like this: 

![image](https://user-images.githubusercontent.com/2660559/230175925-e5a9bf47-9d53-4cdd-8aea-14bd11e276c4.png)

**Comment by yelper** [comment]
this shipped awhile ago, please let me know if you see any instances of numeric enums that don't have an explanation / English display name!
