### ISSUE TITLE
ActionButton States

### ISSUE THREAD

**Issue by ethicus954** [microsoft/powerbi-desktop-samples#59]
Couldn't really find the syntax for the different states for ActionButtons. 
I might overseen it, is this supported ?

I now use:
`"actionButton": {
            "*": {
                "visualHeader": [{
                    "show": true
                }],
                "border": [{
                    "show": false
                }],
                "text":[{
					"show":true
					},
					{
						**"$id": "default",**
						"transparency": 0,
						"fontColor": {"solid":{"color":"#D91F43"}},
						"fontFamily": "Arial",
						"bold": false
					},
					{
						**"$id": "hover",**
						"transparency": 0,
						"fontColor": {"solid":{"color":"#ffffff"}},
						"fontFamily": "Arial",
						"bold": false
					},
					{
						**"$id": "selected",**
						"transparency": 0,
						"fontColor": {"solid":{"color":"#ffffff"}},
						"fontFamily": "Arial",
						"bold": false
					}],
              
        }`

**Comment by ethicus954** [comment]
So did figured out that the actionbutton has these states:

"$id": "default",
"$id": "hover",
 "$id": "disabled",

The new page navigation and bookmark navigation uses:
 "$id": "default", 
 "$id": "hover",
"$id": "press",
"$id": "selected",

**Comment by ethicus954** [comment]
Press doesn't seems to work on ActionButton

**Comment by yelper** [comment]
`$id` hints have been added to recent schemas (April onward)
