### ISSUE TITLE
Is it possible to create a theme.json which can set a background image for a specific page?

### ISSUE THREAD

**Issue by saviourofdp** [microsoft/powerbi-desktop-samples#62]
I want to set a different background image per page. Is this possible? Currently I have

```js
{
    "name": "Custom",
    "$schema": "https://raw.githubusercontent.com/microsoft/powerbi-desktop-samples/main/Report%20Theme%20JSON%20Schema/reportThemeSchema-2.115.json",
    "visualStyles": {
        "page": {
            "*": {
                "background": [
                    {
                        "image": {
                            "name": "Background",
                            "scaling": "Fit",
                            "url": "data:image/svg+xml,..."
                        },
                        "transparency": 1
                    }
                ]
            }
        }
    }
}
``` 
I've tried replacing the `*` with page name, displayname and index but it doesn't seem to affect anything (which makes sense, based on the schema).

Thanks

**Comment by MikeCarlo** [comment]
No the theme file applies backgrounds to all pages. 

If you want a different image per page you would need to use a tool like https://themes.PowerBI.tips 

More specifically the feature for building wireframes as this allows you to build each page with different backgrounds.
